### ISSUE TITLE
Printed Output Has Significant Flaws

### ISSUE THREAD

**Issue by ssokolow** [ralfbiedert/cheats.rs#117]
I've noticed that the site redesign has caused serious breakages in both the print and cached PDF output.

* The `noprint` class on the "Fork Me on GitHub ribbon" has no effect.
* Entire sections of the reference which I'd *want* to print are hidden inside `<noprint>` elements.
* Tab widgets which do print are not unrolled, denying access to all but their default tabs.
* Expandable explanations in the memory diagrams print collapsed.
* If I turn off `noprint` to access the stuff I want, bits of your diagrams show up in the top-left of page 1 in print mode. (Honestly, I'd suggest using inline SVG for those rather than abusing things like `position: absolute` and `<table>` to do illustration.)
* If I uncollapse the tab widgets the most obvious way, they overdraw the next section down.

This is how far I got to make a userscript to turn it into desired printable output before I got fed up with how seemingly ordinary tweaks caused strange breakages in the print preview, where the DOM Inspector is very crippled:

```css
/* Stuff that got applied to things I want printed */
noprint, .noprint {
    display: block !important;
}
tabs > tab > panel {
    display: inline !important;
}
explanation { 
    display: inherit !important;
}

/* Hacks to fix 'diagram is shoved to the top-left corner of page 1' bugs 
   revealed by turning off noprint. */

#custom-types + p + datum { position: relative !important; }
#custom-types + p + datum > .hidden { position: relative !important; }

datum[style='margin-right:70px'] { position: relative !important; }
datum[style='margin-right:70px'] code { white-space: nowrap !important; }

datum.spaced[style='padding-bottom:165px'] memory-entry { 
    position: relative !important; 
}
datum.spaced[style='padding-bottom:165px'] visual { 
    margin-right: 10em;
}

/* Stuff that shouldn't be printed but is (or would be after my tweaks) */
body > div:first-child > a.noprint:first-child { 
    /* Hide the GitHub ribbon that isn't hiding properly */
    display: none !important;
}
page-controls, #helloctrl, subtext::after, tabs.lifetimes + footnotes {
    display: none !important;
}
```

Overall, with the bits like the diagrams and the tab widget unrolling, it feels like I'm reverse-engineering your attempts to fight the CSS layout model instead of working with it.
