### ISSUE TITLE
Stray transform in book.css causes annoying horizontal scrolling

### ISSUE THREAD

**Issue by turbo** [ralfbiedert/cheats.rs#62]
I noticed a small amount of horizontal scrolling on this page even though it fits visually within my 1920px wide screen. This is driving me quite mad when I just want to scroll down the page and it flops left and right.

Adding this style

```css
* {
  outline: 1px solid red;
}
```

reveals the culprit to be the `#page` div, which has this style:

```css
@media screen and (min-width: 1050px)
.page {
    transition: 0s;
    /* transform: scale(1.05); */
}
```

The transform is the obvious issue, I don't know why it's even there. Removing it fixes the bug. Transform should basically never be used. In addition to the scrolling issue, it causes the fonts and lines to be rendered with "fuzzy" edges and other artifacts, whose severity depend on the screen size.

See before (forced horizontal scroll): 

![Screenshot from 2019-08-16 23-42-44](https://user-images.githubusercontent.com/8023543/63199955-c0d3db00-c07f-11e9-8384-b282b969310f.png)

And after:

![Screenshot from 2019-08-16 23-42-48](https://user-images.githubusercontent.com/8023543/63200078-2d4eda00-c080-11e9-9ad6-736696e6ef4b.png)

If this is intentional, you should increase the font size and not mess with scaling.
